<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260609000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema — creates all tables with current names (no-op if they already exist)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS "user" (
            id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            firstname   VARCHAR(255) NOT NULL,
            lastname    VARCHAR(255) NOT NULL,
            email       VARCHAR(180) NOT NULL,
            role        VARCHAR(255) NOT NULL,
            password    VARCHAR(255) NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_email ON "user" (email)');

        $this->addSql('CREATE TABLE IF NOT EXISTS supplier (
            id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name          VARCHAR(255) NOT NULL,
            contact_email VARCHAR(180) DEFAULT NULL,
            phone         VARCHAR(20)  DEFAULT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE TABLE IF NOT EXISTS workstation (
            id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR(50)  NOT NULL,
            label     VARCHAR(255) NOT NULL,
            capacity  INT          DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_workstation_reference ON workstation (reference)');

        $this->addSql('CREATE TABLE IF NOT EXISTS machine (
            id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR(50)  NOT NULL,
            label     VARCHAR(255) NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_machine_reference ON machine (reference)');

        $this->addSql('CREATE TABLE IF NOT EXISTS part (
            id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference      VARCHAR(50)        NOT NULL,
            label          VARCHAR(255)       NOT NULL,
            type           VARCHAR(255)       NOT NULL,
            sale_price     DOUBLE PRECISION   DEFAULT NULL,
            stock_quantity INT                NOT NULL DEFAULT 0,
            supplier_id    INT                DEFAULT NULL,
            catalog_price  DOUBLE PRECISION   DEFAULT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_part_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_part_reference ON part (reference)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_part_supplier ON part (supplier_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS routing (
            id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference     VARCHAR(50)  NOT NULL,
            label         VARCHAR(255) NOT NULL,
            part_id       INT          NOT NULL,
            supervisor_id INT          NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_routing_part       FOREIGN KEY (part_id)       REFERENCES part   (id) NOT DEFERRABLE,
            CONSTRAINT fk_routing_supervisor FOREIGN KEY (supervisor_id) REFERENCES "user" (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_routing_reference ON routing (reference)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_routing_part       ON routing (part_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_routing_supervisor ON routing (supervisor_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS operation (
            id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            "rank"         INT              NOT NULL,
            label          VARCHAR(255)     NOT NULL,
            unit_time      DOUBLE PRECISION NOT NULL,
            routing_id     INT              NOT NULL,
            workstation_id INT              NOT NULL,
            machine_id     INT              DEFAULT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_operation_routing     FOREIGN KEY (routing_id)     REFERENCES routing     (id) NOT DEFERRABLE,
            CONSTRAINT fk_operation_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id) NOT DEFERRABLE,
            CONSTRAINT fk_operation_machine     FOREIGN KEY (machine_id)     REFERENCES machine     (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_operation_routing     ON operation (routing_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_operation_workstation ON operation (workstation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_operation_machine     ON operation (machine_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS forecast (
            id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            planned_date     DATE         NOT NULL,
            planned_quantity INT          NOT NULL,
            status           VARCHAR(255) NOT NULL,
            operation_id     INT          NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_forecast_operation FOREIGN KEY (operation_id) REFERENCES operation (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_forecast_operation ON forecast (operation_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS completion (
            id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            date            DATE             NOT NULL,
            actual_quantity INT              NOT NULL,
            actual_duration DOUBLE PRECISION DEFAULT NULL,
            operation_id    INT              NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_completion_operation FOREIGN KEY (operation_id) REFERENCES operation (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_completion_operation ON completion (operation_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS bill_of_materials (
            id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            quantity       INT         NOT NULL,
            unit           VARCHAR(20) DEFAULT NULL,
            parent_part_id INT         NOT NULL,
            child_part_id  INT         NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_bom_parent_part FOREIGN KEY (parent_part_id) REFERENCES part (id) NOT DEFERRABLE,
            CONSTRAINT fk_bom_child_part  FOREIGN KEY (child_part_id)  REFERENCES part (id) NOT DEFERRABLE
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_bom_parent_part ON bill_of_materials (parent_part_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_bom_child_part  ON bill_of_materials (child_part_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS password_reset_token (
            id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id    INT                             NOT NULL,
            token      VARCHAR(64)                     NOT NULL,
            expires_at TIMESTAMP(0) WITHOUT TIME ZONE  NOT NULL,
            used_at    TIMESTAMP(0) WITHOUT TIME ZONE  DEFAULT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_prt_token   ON password_reset_token (token)');
        $this->addSql('CREATE INDEX        IF NOT EXISTS idx_prt_user_id  ON password_reset_token (user_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS machine_workstation (
            machine_id     INT NOT NULL,
            workstation_id INT NOT NULL,
            PRIMARY KEY (machine_id, workstation_id),
            CONSTRAINT fk_mw_machine     FOREIGN KEY (machine_id)     REFERENCES machine     (id) ON DELETE CASCADE,
            CONSTRAINT fk_mw_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id) ON DELETE CASCADE
        )');

        $this->addSql('CREATE TABLE IF NOT EXISTS user_workstation (
            user_id        INT NOT NULL,
            workstation_id INT NOT NULL,
            PRIMARY KEY (user_id, workstation_id),
            CONSTRAINT fk_uw_user        FOREIGN KEY (user_id)        REFERENCES "user"      (id) ON DELETE CASCADE,
            CONSTRAINT fk_uw_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id) ON DELETE CASCADE
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS user_workstation');
        $this->addSql('DROP TABLE IF EXISTS machine_workstation');
        $this->addSql('DROP TABLE IF EXISTS password_reset_token');
        $this->addSql('DROP TABLE IF EXISTS bill_of_materials');
        $this->addSql('DROP TABLE IF EXISTS completion');
        $this->addSql('DROP TABLE IF EXISTS forecast');
        $this->addSql('DROP TABLE IF EXISTS operation');
        $this->addSql('DROP TABLE IF EXISTS routing');
        $this->addSql('DROP TABLE IF EXISTS part');
        $this->addSql('DROP TABLE IF EXISTS machine');
        $this->addSql('DROP TABLE IF EXISTS workstation');
        $this->addSql('DROP TABLE IF EXISTS supplier');
        $this->addSql('DROP TABLE IF EXISTS "user"');
    }
}
