<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625065110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fix production_order id to use GENERATED BY DEFAULT AS IDENTITY';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE production_order ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE production_order ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE production_order ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS production_order_id_seq');
        $this->addSql('ALTER TABLE production_order ALTER id SET DEFAULT nextval(\'production_order_id_seq\')');
    }
}
