<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628213249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_quote_line (order_id INT NOT NULL, quote_line_id INT NOT NULL, PRIMARY KEY (order_id, quote_line_id))');
        $this->addSql('CREATE INDEX IDX_F02916298D9F6D38 ON order_quote_line (order_id)');
        $this->addSql('CREATE INDEX IDX_F0291629A294DDC6 ON order_quote_line (quote_line_id)');
        $this->addSql('ALTER TABLE order_quote_line ADD CONSTRAINT FK_F02916298D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_quote_line ADD CONSTRAINT FK_F0291629A294DDC6 FOREIGN KEY (quote_line_id) REFERENCES quote_line (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT fk_9ce58ee14ce34bec');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT fk_9ce58ee18d9f6d38');
        $this->addSql('DROP TABLE order_line');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, order_id INT NOT NULL, part_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9ce58ee18d9f6d38 ON order_line (order_id)');
        $this->addSql('CREATE INDEX idx_9ce58ee14ce34bec ON order_line (part_id)');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT fk_9ce58ee14ce34bec FOREIGN KEY (part_id) REFERENCES part (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT fk_9ce58ee18d9f6d38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_quote_line DROP CONSTRAINT FK_F02916298D9F6D38');
        $this->addSql('ALTER TABLE order_quote_line DROP CONSTRAINT FK_F0291629A294DDC6');
        $this->addSql('DROP TABLE order_quote_line');
    }
}
