<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611085713 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
    $this->addSql('CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, contact_email VARCHAR(180) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE gamme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C32E1468AEA34913 ON gamme (reference)');
        $this->addSql('CREATE INDEX IDX_C32E1468C40FCFA8 ON gamme (piece_id)');
        $this->addSql('CREATE TABLE machine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, poste_de_travail_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1505DF84AEA34913 ON machine (reference)');
        $this->addSql('CREATE INDEX IDX_1505DF8417A47EE6 ON machine (poste_de_travail_id)');
        $this->addSql('CREATE TABLE nomenclature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit VARCHAR(20) DEFAULT NULL, parent_piece_id INT NOT NULL, child_piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_799A36525BC26379 ON nomenclature (parent_piece_id)');
        $this->addSql('CREATE INDEX IDX_799A36524E08B20C ON nomenclature (child_piece_id)');
        $this->addSql('CREATE TABLE poste_de_travail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, capacity INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD84E80AAEA34913 ON poste_de_travail (reference)');
        $this->addSql('ALTER TABLE gamme ADD CONSTRAINT FK_C32E1468C40FCFA8 FOREIGN KEY (piece_id) REFERENCES piece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF8417A47EE6 FOREIGN KEY (poste_de_travail_id) REFERENCES poste_de_travail (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nomenclature ADD CONSTRAINT FK_799A36525BC26379 FOREIGN KEY (parent_piece_id) REFERENCES piece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nomenclature ADD CONSTRAINT FK_799A36524E08B20C FOREIGN KEY (child_piece_id) REFERENCES piece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE piece ADD stock_quantity INT NOT NULL');
        $this->addSql('ALTER TABLE piece ADD stock_min INT NOT NULL');
    $this->addSql('ALTER TABLE piece ADD supplier_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE piece ALTER reference TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE piece ALTER sale_price TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE piece ALTER sale_price DROP NOT NULL');
    $this->addSql('ALTER TABLE piece ADD CONSTRAINT FK_44CA0B23670C757F FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44CA0B23AEA34913 ON piece (reference)');
    $this->addSql('CREATE INDEX IDX_44CA0B23670C757F ON piece (supplier_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE gamme DROP CONSTRAINT FK_C32E1468C40FCFA8');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF8417A47EE6');
        $this->addSql('ALTER TABLE nomenclature DROP CONSTRAINT FK_799A36525BC26379');
        $this->addSql('ALTER TABLE nomenclature DROP CONSTRAINT FK_799A36524E08B20C');
    $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE gamme');
        $this->addSql('DROP TABLE machine');
        $this->addSql('DROP TABLE nomenclature');
        $this->addSql('DROP TABLE poste_de_travail');
        $this->addSql('ALTER TABLE piece DROP CONSTRAINT FK_44CA0B23670C757F');
        $this->addSql('DROP INDEX UNIQ_44CA0B23AEA34913');
        $this->addSql('DROP INDEX IDX_44CA0B23670C757F');
        $this->addSql('ALTER TABLE piece DROP stock_quantity');
        $this->addSql('ALTER TABLE piece DROP stock_min');
    $this->addSql('ALTER TABLE piece DROP supplier_id');
        $this->addSql('ALTER TABLE piece ALTER reference TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE piece ALTER sale_price TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE piece ALTER sale_price SET NOT NULL');
    }
}
