<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611093758 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rang INT NOT NULL, label VARCHAR(255) NOT NULL, temps_unitaire DOUBLE PRECISION NOT NULL, gamme_id INT NOT NULL, poste_de_travail_id INT NOT NULL, machine_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1981A66DD2FD85F1 ON operation (gamme_id)');
        $this->addSql('CREATE INDEX IDX_1981A66D17A47EE6 ON operation (poste_de_travail_id)');
        $this->addSql('CREATE INDEX IDX_1981A66DF6B75B26 ON operation (machine_id)');
        $this->addSql('CREATE TABLE prevision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_prevue DATE NOT NULL, quantite_prevue INT NOT NULL, statut VARCHAR(255) NOT NULL, operation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1EEB1DDE44AC3583 ON prevision (operation_id)');
        $this->addSql('CREATE TABLE realisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, quantite_realisee INT NOT NULL, duree_reelle DOUBLE PRECISION DEFAULT NULL, operation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAA5610E44AC3583 ON realisation (operation_id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DD2FD85F1 FOREIGN KEY (gamme_id) REFERENCES gamme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D17A47EE6 FOREIGN KEY (poste_de_travail_id) REFERENCES poste_de_travail (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DF6B75B26 FOREIGN KEY (machine_id) REFERENCES machine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prevision ADD CONSTRAINT FK_1EEB1DDE44AC3583 FOREIGN KEY (operation_id) REFERENCES operation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realisation ADD CONSTRAINT FK_EAA5610E44AC3583 FOREIGN KEY (operation_id) REFERENCES operation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66DD2FD85F1');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66D17A47EE6');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66DF6B75B26');
        $this->addSql('ALTER TABLE prevision DROP CONSTRAINT FK_1EEB1DDE44AC3583');
        $this->addSql('ALTER TABLE realisation DROP CONSTRAINT FK_EAA5610E44AC3583');
        $this->addSql('DROP TABLE operation');
        $this->addSql('DROP TABLE prevision');
        $this->addSql('DROP TABLE realisation');
    }
}
